# Use a standard Node.js image that includes essential build tools 
# 'bullseye-slim' is a good balance of size and functionality.
FROM node:18-bullseye-slim

# Set the working directory inside the container
WORKDIR /app

# Copy lock file and package.json and install dependencies
# This is done first to cache dependency installation
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Run the build script to create the 'dist' folder
RUN npm run build

# Set the default environment port (Railway will map this)
ENV PORT 3000
EXPOSE 3000

# Define the command to start the application
CMD ["npm", "run", "start"]